### PR TITLE
Bug Support Back-end

### PR DESCRIPTION
**Pull request by TheGamerzs**

### CODE REVIEW

**Comment by TheGamerzs** [comment]
It’s to check it’s actually a user

**Comment by TheGamerzs** [comment]
> You are requesting the user token, but you are not doing anything with it.

To check it’s actually a user

**Comment by OfficialCRUGG** [comment]
I just quickly looked over the code and I'm not completely sure, but to me it looks like yeah you check if there's a code but that's unnecessary since I could just enter "123" as the code.
Like there's 0 Validation of what the Content is the Code is.
@TheGamerzs

**Comment by OfficialCRUGG** [comment]
Wouldn't it be super easy to spam thousands of Bug Reports though?

**Comment by TheGamerzs** [comment]
Needs Collection: 'bugs' and 'bugUsers'

**Pull request merged**
